// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// DropboxWrapper is an autogenerated mock type for the DropboxWrapper type
type DropboxWrapper struct {
	mock.Mock
}

// Uplaod provides a mock function with given fields: ctx, file, pathFolder
func (_m *DropboxWrapper) Uplaod(ctx context.Context, file *multipart.FileHeader, pathFolder string) (string, error) {
	ret := _m.Called(ctx, file, pathFolder)

	if len(ret) == 0 {
		panic("no return value specified for Uplaod")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) (string, error)); ok {
		return rf(ctx, file, pathFolder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, string) string); ok {
		r0 = rf(ctx, file, pathFolder)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, string) error); ok {
		r1 = rf(ctx, file, pathFolder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDropboxWrapper creates a new instance of DropboxWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDropboxWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *DropboxWrapper {
	mock := &DropboxWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
